export const productTypes = {
  FILTERBYSELECT: "FILTERBYSELECT",
  FILTERBYSTATE: "FILTERBYSTATE",
  FILTERBYSORT: "FILTERBYSORT",
  FILTERBYRANGE: "FILTERBYRANGE",
  FILTERBYCHECKBOX: "FILTERBYCHECKBOX",
  FILTERBYTEXT: "FILTERBYTEXT",
  CHANGEVIEW: "CHANGEVIEW",
  UPDATEFILTERS: "UPDATEFILTERS",
  RESET: "RESET",
  RESETFILTERS: "RESETFILTERS",
};



